### Get all data movies
GET http://localhost:1234/movies

### Get specific movie by id
GET http://localhost:1234/movies/1ded44fa-622c-11ee-9b3f-0242ac110002

### Get all movies by genre
GET http://localhost:1234/movies?genre=action

### Create new movie
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppla",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Crime",
        "Drama"
    ]
}

### Delete movie
DELETE http://localhost:1234/movies/97f7041b-6234-11ee-9b3f-0242ac110002

### Update movie
PATCH http://localhost:1234/movies/20ec5207-6236-11ee-9b3f-0242ac110002
Content-Type: application/json

{
    "year": 2003
}